# Scalar
A scalar usually denotes a single number as opposed to a collection of numbers. A simple example might be x=5 or $x \in \mathbb{R}$, where x is the scalar element pointing to a single number or a real-valued single number.

# Vector
A *vector* is defined as a structure that holds an array of numbers which are arranged in order. 

In [1]:
x = [1,2,3,4,5]

In [2]:
import numpy as np
x = np.array(x)

In [3]:
print(x,type(x))

[1 2 3 4 5] <class 'numpy.ndarray'>


# Matrix

A *matrix is a two-dimensional strcuture that basically holds numbers. It's also often referred to as a 2D array.
Mathematically, you can depict a matrix as $M = \begin{bmatrix}
 m_{11} & m_{12}  & m_{13} \\ 
 m_{21} &  m_{22}  &  m_{23} \\ 
 m_{31} &   m_{32} &  m_{33} \\  
\end{bmatrix}$ 
such that M is a 3x3 matrix.

In [4]:
M = np.array([[1,5,2],
              [4,7,4],
              [2,0,9]])

In [7]:
print(M)

[[1 5 2]
 [4 7 4]
 [2 0 9]]


In [8]:
print(M.shape)

(3, 3)


In [10]:
# Matrix Transpose
print(M.transpose())

[[1 4 2]
 [5 7 0]
 [2 4 9]]


In [11]:
# Matrix Determinant
print(np.linalg.det(M))

-105.0


In [12]:
# Matrix Inverse
M_INV = np.linalg.inv(M)

In [16]:
# Identity matrix (result of matrix x matrix_inverse)
IDEN_M = np.dot(M, M_INV)
IDEN_M = np.round(np.abs(IDEN_M), 0 )
print(IDEN_M)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Tensor
A tensor is a generic array. Tensors are basically arrays with a variable number of axes. An element in a three-dimensional tensor T can be denoted by $T_{x,y,z}$ where x,y,z denote the three axes for specifying element T.

# Norm
The *norm* is a measure that is used to compute the size of a vector often also defined as the measure of distance from the origin to the point denoted by the vecotr. Mathematically the *p*th norm of a vector is denoted follows.
$$ L^{p} = \left \| x_{p} \right \| = \left ( \sum_{i}\left | x_{i} \right |^{p}   \right ) ^{\frac{1}{p}}$$

such that $p \geq 1$ and $p \in R$.

# Eigen Decomposition
This is bascially a matrix decomposition process such that we decompose or break down a matrix into a set of eigen vectors and eigen values. The eigen decomposition of a matrix can be mathematically denoted by $M = Vdiag(\lambda)V^{-1}$ such that the matrix M has a total of n linearly independent eigen vectors represented as $
v^{(1)}, v^{(2)}, ... ,v^{(n)} $ and their corresponding  eigen values can be represented as $\lambda_{1},\lambda_{2},...,\lambda_{n}$

In [19]:
# eigendecomposition
m = np.array([[1,5,2],
              [4,7,4],
              [2,0,9]
              ])
eigen_vals, eigen_vecs = np.linalg.eig(m)
print(eigen_vals)
print(eigen_vecs)

[ -1.32455532  11.32455532   7.        ]
[[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]]


In [26]:
np.round( np.dot( np.dot(eigen_vecs, np.diag(eigen_vals)) , np.linalg.inv(eigen_vecs) ) )

array([[ 1.,  5.,  2.],
       [ 4.,  7.,  4.],
       [ 2., -0.,  9.]])

# Single Value Decomposition
The process of single value decomposition, also known as SVD, is another matrix decomposition or factorization process such that we are able to break down a matrix to obtain singular vectors and singular values. Any real matrix will always be decompoed by SVD even if eigen decomposition may not be applicable in some cases. Mathematically, SVD can defined as follows. Considering a matrix $M$ having dimension * m x n * such that *m* denotes total rows and n denotes total columns, the SVD of the matrxi can be represented with the following equation.
$$ M_{m\times n} = U_{m\times m}  S_{m\times n} V_{n\times n} ^{T} $$
This gives us the following main components of the decomposition equation.
* $U_{m\times n}$ is an $ m \times m $ unitary matrix where each column represents a left singular vector
* $S_{m\times n}$ is an $ m \times n $ matrix with positive numbers on the diagonal, which can also be represented as a vector of the singular values.
* $V_{n\times n} ^{T}$ is an $n \times n$ unitary matrix where each row represents a right singular value.

U and V are always orthogonal.

In [29]:
# SVD
U, S, VT = np.linalg.svd(m)
print("U:", U)
print("S:", S)
print("VT:", VT)

U: [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]]
S: [ 12.10668383   6.91783499   1.25370079]
VT: [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]]


# Random Variable
Used frequently in probability and uncertainty measurement, a *random variable* is basically a variable that can take on various values at random. These variables can be of discrete or continuous type in general.

# Probability Distribution
A probability distribution is a distribution or arragnement that depicts the likelihood of a random varaible or variabel to take on each of its probable states. There are usually two main types of distributions based on the variable being discrete or continuous.

# Probability Mass Function
A *probability mass function*, also known as PMF, is a probability distribution over discrete random variables. Popular examples include the Poisson and binomail distributions.

# Probability Density Function
A *probability density function*, also known as PDF, is a probability distribution over continuous random variables. Popular examples include the normal, uniform, and student's T distributions.

# Marginal Probability
The *marginal probability* rule is used when we already have the probability distribution for a set of random variables and we want to compute the probability distribution for a subset of these random variables. For discrete random variables, we can define marginal probability as follows.
$$P(x) = \sum_{y}P(x,y)$$
For continuous random variables, we can define it using the integration operation as follows.
$$p(x) = \int p(x,y)dy$$

# Conditional Probability
The *conditional probability* rule is used when we want to determine the probability that an event is going to take place, such that another event has already taken place. This is mathematically represented as follows.
$$P(x|y) = \frac{P(x,y)}{P(y)}$$
This tells us the conditional probability of x, given that y has already taken place.

# Bayes Theorem
$$P(A|B) = \frac{P(B|A)P(A)}{P(B)}$$
such that A and B are events and 
$P(B) = \sum_{x}P(B|A)P(A)$

# Statistics
* Descriptive statistics
* Inferential statistics
    * test hypothesis, draw inferences, and conclusions about various characteristics of our data sample or population. Frameworks and techniques like hypothesis testing, correlation, and regression analysis, forecasting, and predictions are typically used for any form of inferential statistics.

In [32]:
# descriptive statisitcs
import scipy as sp
import numpy as np

# get data
nums = np.random.randint(1,20, size=(1,15))[0]
print("Data:", nums)

Data: [ 2  8  2  2  7  1 17  2 13 11  6 11 13 15 15]


In [42]:
# get descriptive stats
print("Mean:", sp.mean(nums))
print("Median:", sp.median(nums))
print("Mode:", sp.stats.mode(nums))
print("Standard Deviation:", sp.std(nums))
print("Variance:", sp.var(nums))
print("Skew:", sp.stats.skew(nums))
print("Kurtosis:", sp.stats.kurtosis(nums))

Mean: 8.33333333333
Median: 8.0
Mode: ModeResult(mode=array([2]), count=array([4]))
Standard Deviation: 5.43650214343
Variance: 29.5555555556
Skew: 0.024525573579398243
Kurtosis: -1.473441121600995


# Data Mining
# Artifical Intelligence

# Natural Language Processing
* Machine translation
* Speech Recognition
* Question answering systems
* Context recognition and resolution
* Text summarization
* Text categorization
* Information extraction
* Sentiment and emotion analysis
* Topic segmentation