In [1]:
# source : http://www.machinelearningplus.com/101-numpy-exercises-python/

In [2]:
# 1 Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.13.3


In [6]:
# 2 How to create a 1D array?
q2 = np.arange(0,10)
q2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# 3 How to create a boolean array?
q3 = np.full((3,3), True) # or np.ones((3,3), dtype)
q3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [14]:
# 4 How to extract items that satisfy a given condition from 
#   1D array?
q4 = np.arange(10)
q4[q4%2==1] # Extract all odd numbers

array([1, 3, 5, 7, 9])

In [17]:
# 5 How to replace items that satisfy a condition with another 
# value in numpy array?
q5 = np.arange(10)
q5[q5%2==1]=-1 # Replace all odd numbers with -1
q5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
# 6 How to replace items that satisfy a condition without 
#   affecting the original array?
q6 = np.arange(10)
q6c = q6.copy()
q6c[q6c%2==1]=-1
print(q6)
q6c

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [33]:
# 7 How to reshape an array?
q7 = np.arange(10)
q7b = q7.reshape((2,5)) # convert 1-d array to 2d array
q7c = q7.reshape((2,-1)) # -1 automatically decidess the number of cols
print(q7b)
q7c

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
# 8 How to stack two arrays vertically?
q8a = np.arange(10).reshape(2,-1)
q8b = np.repeat(1,10).reshape(2,-1)
# Method 1
q8c = np.vstack([q8a,q8b])

# Method 2
q8c = np.concatenate([q8a, q8b], axis=0)

# Method 3
q8c = np.r_[q8a, q8b]

q8c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
# 9 How to stack two arrays horizontally?
q9a = np.arange(10).reshape(2,-1)
q9b = np.repeat(1,10).reshape(2,-1)

q9c = np.hstack([q9a,q9b])

q9c = np.concatenate([q9a,q9b], axis=1)

q9c = np.c_[q9a,q9b]
q9c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [61]:
# 10 How to generate custom sequences in numpy
#  without hardcoding?
q10 = np.array([1,2,3])
q10b = np.hstack([np.repeat(q10,3), np.tile(q10, 3)])
q10b

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [65]:
# 11 How to get the common items between two python numpy arrays?
q11a = np.array([1,2,3,2,3,4,3,4,5,6])
q11b = np.array([7,2,10,2,7,4,9,4,9,8])
q11c = np.intersect1d(q11a, q11b)
q11c

array([2, 4])

In [68]:
# 12 How to remove from one array those items that exist in another?
q12a = np.array([1,2,3,4,5])
q12b = np.array([5,6,7,8,9])
q13c = np.setdiff1d(q12a,q12b)
q13c

array([1, 2, 3, 4])