In [1]:
# source : http://www.machinelearningplus.com/101-numpy-exercises-python/

In [2]:
# 1 Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.13.3


In [6]:
# 2 How to create a 1D array?
q2 = np.arange(0,10)
q2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# 3 How to create a boolean array?
q3 = np.full((3,3), True) # or np.ones((3,3), dtype)
q3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [14]:
# 4 How to extract items that satisfy a given condition from 
#   1D array?
q4 = np.arange(10)
q4[q4%2==1] # Extract all odd numbers

array([1, 3, 5, 7, 9])

In [17]:
# 5 How to replace items that satisfy a condition with another 
# value in numpy array?
q5 = np.arange(10)
q5[q5%2==1]=-1 # Replace all odd numbers with -1
q5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
# 6 How to replace items that satisfy a condition without 
#   affecting the original array?
q6 = np.arange(10)
q6c = q6.copy()
q6c[q6c%2==1]=-1
print(q6)
q6c

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [33]:
# 7 How to reshape an array?
q7 = np.arange(10)
q7b = q7.reshape((2,5)) # convert 1-d array to 2d array
q7c = q7.reshape((2,-1)) # -1 automatically decidess the number of cols
print(q7b)
q7c

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
# 8 How to stack two arrays vertically?
q8a = np.arange(10).reshape(2,-1)
q8b = np.repeat(1,10).reshape(2,-1)
# Method 1
q8c = np.vstack([q8a,q8b])

# Method 2
q8c = np.concatenate([q8a, q8b], axis=0)

# Method 3
q8c = np.r_[q8a, q8b]

q8c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
# 9 How to stack two arrays horizontally?
q9a = np.arange(10).reshape(2,-1)
q9b = np.repeat(1,10).reshape(2,-1)

q9c = np.hstack([q9a,q9b])

q9c = np.concatenate([q9a,q9b], axis=1)

q9c = np.c_[q9a,q9b]
q9c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [61]:
# 10 How to generate custom sequences in numpy
#  without hardcoding?
q10 = np.array([1,2,3])
q10b = np.hstack([np.repeat(q10,3), np.tile(q10, 3)])
q10b

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [65]:
# 11 How to get the common items between two python numpy arrays?
q11a = np.array([1,2,3,2,3,4,3,4,5,6])
q11b = np.array([7,2,10,2,7,4,9,4,9,8])
q11c = np.intersect1d(q11a, q11b)
q11c

array([2, 4])

In [68]:
# 12 How to remove from one array those items that exist in another?
q12a = np.array([1,2,3,4,5])
q12b = np.array([5,6,7,8,9])
q13c = np.setdiff1d(q12a,q12b)
q13c

array([1, 2, 3, 4])

In [80]:
# 13 How to get the positions where elements of two arrays match?
q13a = np.array([1,2,3,2,3,4,3,4,5,6])
q13b = np.array([7,2,10,2,7,4,9,4,9,8])

q13c = np.where(q13a==q13b)
q13d = np.argwhere(q13a==q13b).ravel()
print(q13c)
q13d

(array([1, 3, 5, 7]),)


array([1, 3, 5, 7])

In [91]:
# 14 How to extract all numbers between a given range from a 
#   numpy array?
q14a = np.arange(15)
q14a[(q14a>5) & (q14a<=10)] # Get all items between 5 and 10

array([ 6,  7,  8,  9, 10])

In [101]:
# 15 How to make a python function that handles scalars to work on 
#  numpy arrays?
q15a = np.array([5, 7, 9, 8, 6, 4, 5])
q15b = np.array([6, 3, 4, 8, 9, 7, 1])

def maxx(x,y):
    if x>=y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx)
pair_max(q15a, q15b)

array([6, 7, 9, 8, 9, 7, 5])

In [108]:
# 16 How to swap two columns in a 2d numpy array?
q16 = np.arange(9).reshape(3,3)
q16[:, [1,0,2]] # swap columns 1 and 2 in the array

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [110]:
# 17 How to swap two rows in a 2d numpy array?
q17 = np.arange(9).reshape(3,3)
q17[[1,0,2],:] # swap rows 1 and 2 in the array

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [118]:
# 18 How to reverse the rows of a 2d array?
q18 = np.arange(9).reshape(3,3)
q18[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [142]:
# 19 How to reverse the columns of a 2d array?
q19 = np.arange(9).reshape(3,3)
q19[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [153]:
# 20 How to create a 2D array containing random floats between
#    5 and 10?
q20 = np.random.uniform(5,10, size=(5,3))
# np.random.randint(5,10,size=(5,3)) + np.random.random((5,3))
q20

array([[ 7.66361199,  9.39039882,  9.41225952],
       [ 5.01504393,  9.52829588,  5.36651003],
       [ 9.18511077,  5.76961014,  6.06072003],
       [ 7.40544564,  5.42673118,  8.18967393],
       [ 5.42975364,  6.21694699,  8.31330047]])

In [162]:
# 21 How to print only 3 decimal places in python numpy array?
q21 = np.random.random((5,3))
np.set_printoptions(precision=3)
# q21.round(3) 

In [174]:
# 22 How to pretty print a numpy array by suppressing the 
#    scientific notation (like 1e10)?
np.random.seed(100)
q22 = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True,precision=6)
q22

array([[ 0.000543,  0.000278,  0.000425],
       [ 0.000845,  0.000005,  0.000122],
       [ 0.000671,  0.000826,  0.000137]])

In [180]:
# 23 How to limit the number of items printed in output
#    of numpy array?
q23 = np.arange(15)
np.set_printoptions(threshold=6)
q23

array([ 0,  1,  2, ..., 12, 13, 14])

In [181]:
# 24 How to print the full numpy array without truncating
q24 = np.arange(15)
np.set_printoptions(threshold=None)
q24

array([ 0,  1,  2, ..., 12, 13, 14])